# Generated by Django 4.2 on 2023-04-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_reviewmodel_product_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='size',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='product_info',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
